export interface IssueLabelRule {
  keywords: string[];
  label: { name: string; color: string; description: string };
}

export const ISSUE_LABEL_RULES: IssueLabelRule[] = [
  {
    keywords: [
      "bug",
      "broken",
      "crash",
      "error",
      "exception",
      "failure",
      "fails",
      "failing",
      "not working",
      "unexpected behavior",
      "regression",
      "glitch",
      "freeze",
      "hang",
      "stack trace",
      "issue",
      "problem",
    ],
    label: {
      name: "bug",
      color: "D73A4A",
      description: "Something isn't working",
    },
  },

  {
    keywords: [
      "feature",
      "feature request",
      "enhancement",
      "improvement",
      "proposal",
      "suggestion",
      "idea",
      "would like",
      "please add",
      "add support",
      "new functionality",
      "new capability",
      "qol",
      "quality of life",
    ],
    label: {
      name: "enhancement",
      color: "A2EEEF",
      description: "New feature or request",
    },
  },

  {
    keywords: [
      "question",
      "how do i",
      "how to",
      "help",
      "support",
      "usage",
      "example",
      "clarification",
      "why",
      "can i",
      "does it support",
      "getting started",
    ],
    label: {
      name: "question",
      color: "D876E3",
      description: "Further information is requested",
    },
  },

  {
    keywords: [
      "docs",
      "documentation",
      "readme",
      "wiki",
      "tutorial",
      "guide",
      "api docs",
      "typo",
      "spelling",
      "grammar",
      "broken link",
      "dead link",
      "comment",
      "markdown",
    ],
    label: {
      name: "docs",
      color: "0075CA",
      description: "Improvements or additions to documentation",
    },
  },

  {
    keywords: [
      "security",
      "vulnerability",
      "cve",
      "exploit",
      "xss",
      "csrf",
      "rce",
      "sql injection",
      "injection",
      "auth bypass",
      "authentication",
      "authorization",
      "permission bypass",
      "token leak",
      "secret leak",
      "credential leak",
      "sensitive data",
      "security issue",
    ],
    label: {
      name: "security",
      color: "B60205",
      description: "Security-related issue",
    },
  },

  {
    keywords: [
      "performance",
      "slow",
      "sluggish",
      "lag",
      "laggy",
      "high cpu",
      "cpu usage",
      "memory usage",
      "memory leak",
      "optimization",
      "optimize",
      "benchmark",
      "throughput",
      "latency",
      "resource usage",
      "takes too long",
    ],
    label: {
      name: "perf",
      color: "FBCA04",
      description: "Performance improvements or issues",
    },
  },

  {
    keywords: [
      "ui",
      "ux",
      "layout",
      "design",
      "styling",
      "css",
      "theme",
      "responsive",
      "mobile",
      "desktop",
      "button",
      "dropdown",
      "modal",
      "visual",
      "appearance",
      "user interface",
    ],
    label: {
      name: "style",
      color: "5319E7",
      description: "User interface and design related",
    },
  },

  {
    keywords: [
      "test",
      "testing",
      "unit test",
      "integration test",
      "e2e",
      "coverage",
      "test case",
      "failing test",
      "mock",
      "assertion",
    ],
    label: {
      name: "test",
      color: "C2E0C6",
      description: "Tests and test infrastructure",
    },
  },

  {
    keywords: [
      "ci",
      "github actions",
      "workflow",
      "pipeline",
      "build failure",
      "deployment",
      "deploy",
      "release pipeline",
      "automation",
    ],
    label: {
      name: "ci",
      color: "1D76DB",
      description: "Continuous integration and deployment",
    },
  },

  {
    keywords: [
      "dependencies",
      "dependency",
      "package",
      "upgrade",
      "update dependency",
      "npm",
      "pnpm",
      "yarn",
      "bun",
      "version bump",
      "package update",
    ],
    label: {
      name: "chore",
      color: "0366D6",
      description: "Dependency updates and issues",
    },
  },

  {
    keywords: [
      "good first issue",
      "beginner",
      "starter",
      "easy fix",
      "easy issue",
      "new contributor",
      "first contribution",
    ],
    label: {
      name: "good first issue",
      color: "7057FF",
      description: "Suitable for first-time contributors",
    },
  },
];
