export interface IssueLabelRule {
  keywords: string[];
  label: { name: string; color: string; description: string };
}

export const ISSUE_LABEL_RULES: IssueLabelRule[] = [
  {
    keywords: [
      "bug",
      "broken",
      "crash",
      "crashes",
      "crashing",
      "error",
      "exception",
      "failure",
      "fails",
      "failing",
      "doesn't work",
      "does not work",
      "not working",
      "unexpected behavior",
      "regression",
      "glitch",
      "freeze",
      "freezes",
      "frozen",
      "unresponsive",
      "stuck",
      "stack trace",
      "problem",
    ],
    label: {
      name: "bug",
      color: "D73A4A",
      description: "Something isn't working",
    },
  },

  {
    keywords: [
      "feature",
      "feature request",
      "enhancement",
      "improvement",
      "proposal",
      "suggestion",
      "idea",
      "would like",
      "please add",
      "add support",
      "new functionality",
      "new capability",
      "qol",
      "quality of life",
    ],
    label: {
      name: "enhancement",
      color: "A2EEEF",
      description: "New feature or request",
    },
  },

  {
    keywords: [
      "question",
      "how do i",
      "how to",
      "how can i",
      "clarification",
      "getting started",
      "can i use",
      "does it support",
      "what is the difference",
      "is it possible to",
      "not sure how",
      "could someone explain",
      "any way to",
      "usage example",
    ],
    label: {
      name: "question",
      color: "D876E3",
      description: "Further information is requested",
    },
  },

  {
    keywords: [
      "docs",
      "documentation",
      "readme",
      "wiki",
      "tutorial",
      "guide",
      "api docs",
      "typo",
      "spelling",
      "grammar",
      "broken link",
      "dead link",
      "markdown",
    ],
    label: {
      name: "docs",
      color: "0075CA",
      description: "Improvements or additions to documentation",
    },
  },

  {
    keywords: [
      "security",
      "vulnerability",
      "cve",
      "exploit",
      "xss",
      "csrf",
      "sql injection",
      "command injection",
      "remote code execution",
      "arbitrary code execution",
      "auth bypass",
      "permission bypass",
      "privilege escalation",
      "unauthorized access",
      "token leak",
      "secret leak",
      "credential leak",
      "sensitive data exposure",
      "security issue",
    ],
    label: {
      name: "security",
      color: "B60205",
      description: "Security-related issue",
    },
  },

  {
    keywords: [
      "performance",
      "slow",
      "sluggish",
      "laggy",
      "high cpu",
      "cpu usage",
      "memory usage",
      "memory leak",
      "optimization",
      "optimize",
      "benchmark",
      "throughput",
      "latency",
      "resource usage",
      "takes too long",
    ],
    label: {
      name: "perf",
      color: "FBCA04",
      description: "Performance improvements or issues",
    },
  },

  {
    keywords: [
      "ui bug",
      "ux issue",
      "layout issue",
      "design",
      "styling",
      "css",
      "theme",
      "responsive design",
      "mobile layout",
      "desktop layout",
      "button styling",
      "modal design",
      "dropdown ui",
      "component styling",
      "visual glitch",
      "user interface",
    ],
    label: {
      name: "style",
      color: "5319E7",
      description: "User interface and design related",
    },
  },

  {
    keywords: [
      "testing",
      "unit test",
      "integration test",
      "e2e",
      "coverage",
      "test case",
      "test suite",
      "failing test",
      "mock",
      "assertion",
    ],
    label: {
      name: "test",
      color: "C2E0C6",
      description: "Tests and test infrastructure",
    },
  },

  {
    keywords: [
      "github actions",
      "ci pipeline",
      "ci/cd",
      "workflow failure",
      "build failure",
      "deployment pipeline",
      "release pipeline",
      "continuous integration",
    ],
    label: {
      name: "ci",
      color: "1D76DB",
      description: "Continuous integration and deployment",
    },
  },

  {
    keywords: [
      "dependencies",
      "dependency",
      "npm",
      "pnpm",
      "yarn",
      "bun install",
      "bun.lockb",
      "bunfig",
      "package.json",
      "package upgrade",
      "package update",
      "dependency update",
      "bump dependency",
      "outdated dependency",
      "lockfile",
      "peer dependency",
      "version bump",
    ],
    label: {
      name: "chore",
      color: "0366D6",
      description: "Dependency updates and issues",
    },
  },

  {
    keywords: [
      "good first issue",
      "beginner",
      "starter",
      "easy fix",
      "easy issue",
      "new contributor",
      "first contribution",
    ],
    label: {
      name: "good first issue",
      color: "7057FF",
      description: "Suitable for first-time contributors",
    },
  },
];
