import { readFileSync } from "fs";
import { dirname, join } from "path";
import { Context } from "probot";
import ucid from "unique-custom-id";
import { fileURLToPath } from "url";
import { defineEventHandler } from "../../lib/eventHandler.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

const LINT_WORKFLOW_PATHS = [
  ".github/workflows/linter.yaml",
  ".github/workflows/linter.yml",
];

async function fileExists(
  context: Context<"issue_comment.created">,
  owner: string,
  repo: string,
  path: string,
): Promise<boolean> {
  try {
    await context.octokit.rest.repos.getContent({ owner, repo, path });
    return true;
  } catch {
    return false;
  }
}

export default defineEventHandler({
  events: ["issue_comment.created"],
  callback: async (context) => {
    const body = context.payload.comment.body.trim();

    if (!body.startsWith("!addlinter")) return;

    const { owner, repo } = context.repo();
    const username = context.payload.sender.login;

    const { data: permission } =
      await context.octokit.rest.repos.getCollaboratorPermissionLevel({
        owner,
        repo,
        username,
      });

    const allowed = ["admin", "maintain"];

    if (!allowed.includes(permission.permission)) {
      await context.octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: context.payload.issue.number,
        body: "❌ You must be a repository administrator to use this command.",
      });

      return;
    }

    for (const path of LINT_WORKFLOW_PATHS) {
      if (await fileExists(context, owner, repo, path)) {
        await context.octokit.rest.issues.createComment(
          context.issue({
            body: [
              "> [!NOTE]",
              `> A lint workflow already exists at \`${path}\`. Nothing to do!`,
            ].join("\n"),
          }),
        );
        return;
      }
    }

    const branchName = `devhub-bot/${ucid.format("mini")}`;
    const workflowPath = ".github/workflows/linter.yaml";

    const lintWorkflowContent = readFileSync(
      join(__dirname, "../../templates/linter.yml"),
      "utf-8",
    );

    const encodedContent = Buffer.from(lintWorkflowContent).toString("base64");

    const { data: mainRef } = await context.octokit.rest.git.getRef({
      owner,
      repo,
      ref: "heads/main",
    });
    const mainSha = mainRef.object.sha;

    await context.octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: mainSha,
    });

    await context.octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: workflowPath,
      message: "ci: add lint workflow",
      content: encodedContent,
      branch: branchName,
    });

    const { data: pr } = await context.octokit.rest.pulls.create({
      owner,
      repo,
      title: "ci: add lint workflow",
      head: branchName,
      base: "main",
      body: [
        "This PR adds a GitHub Actions lint workflow to the repository.",
        "",
        "It was automatically generated by **devhub-bot** in response to the `!addlinter` command.",
        "",
      ].join("\n"),
    });

    await context.octokit.rest.issues.createComment(
      context.issue({
        body: [
          "> [!NOTE]",
          `> Done! I've opened a PR to add the lint workflow (#${pr.number})`,
        ].join("\n"),
      }),
    );
  },
});
